export const ADD_REMINDER = "ADD_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const CLEAR_REMINDERS = "CLEAR_REMINDERS";

export const ADD_TARGET = "ADD_TARGET";
export const DELETE_TARGET = "DELETE_TARGET";
export const CLEAR_TARGETS = "CLEAR_TARGETS";
